#pragma once

#define WORLDMACHINE(x) WORLDMACHINE_PRIVATE_DEFINITION_##x()


#ifndef WORLDMACHINE_CPP_INTERFACE
#if __cplusplus && !__METAL_VERSION__
#define WORLDMACHINE_PRIVATE_DEFINITION_CPP() 1
#else // __cplusplus
#define WORLDMACHINE_PRIVATE_DEFINITION_CPP() 0
#endif // __cplusplus
#else // WORLDMACHINE_CPP_INTERFACE
#define WORLDMACHINE_PRIVATE_DEFINITION_CPP() WORLDMACHINE_CPP_INTERFACE()
#endif // WORLDMACHINE_CPP_INTERFACE

#ifndef WORLDMACHINE_MTL_INTERFACE
#if __METAL_VERSION__
#define WORLDMACHINE_PRIVATE_DEFINITION_MTL() 1
#else // __METAL_VERSION__
#define WORLDMACHINE_PRIVATE_DEFINITION_MTL() 0
#endif // __METAL_VERSION__
#else // WORLDMACHINE_MTL_INTERFACE
#define WORLDMACHINE_PRIVATE_DEFINITION_MTL() WORLDMACHINE_MTL_INTERFACE()
#endif // WORLDMACHINE_MTL_INTERFACE

#if WORLDMACHINE(CPP)
#define WORLDMACHINE_PRIVATE_DEFINITION_CONSTANT() inline constexpr
#elif WORLDMACHINE(MTL)
#define WORLDMACHINE_PRIVATE_DEFINITION_CONSTANT() constant
#endif


#define WORLDMACHINE_API __attribute__((visibility("default")))
