#pragma once


vec<T, 2, math_internal::make_swizzle_options(O, 1, 1)> xx;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 2)> xy;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 3)> xz;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 1)> yx;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 2)> yy;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 3)> yz;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 1)> zx;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 2)> zy;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 3)> zz;

vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 1)> xxx;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 2)> xxy;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 3)> xxz;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 1)> xyx;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 2)> xyy;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 3)> xyz;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 1)> xzx;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 2)> xzy;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 3)> xzz;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 1)> yxx;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 2)> yxy;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 3)> yxz;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 1)> yyx;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 2)> yyy;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 3)> yyz;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 1)> yzx;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 2)> yzy;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 3)> yzz;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 1)> zxx;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 2)> zxy;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 3)> zxz;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 1)> zyx;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 2)> zyy;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 3)> zyz;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 1)> zzx;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 2)> zzy;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 3)> zzz;

vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 1)> xxxx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 2)> xxxy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 3)> xxxz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 1)> xxyx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 2)> xxyy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 3)> xxyz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 1)> xxzx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 2)> xxzy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 3)> xxzz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 1)> xyxx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 2)> xyxy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 3)> xyxz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 1)> xyyx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 2)> xyyy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 3)> xyyz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 1)> xyzx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 2)> xyzy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 3)> xyzz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 1)> xzxx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 2)> xzxy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 3)> xzxz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 1)> xzyx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 2)> xzyy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 3)> xzyz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 1)> xzzx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 2)> xzzy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 3)> xzzz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 1)> yxxx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 2)> yxxy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 3)> yxxz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 1)> yxyx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 2)> yxyy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 3)> yxyz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 1)> yxzx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 2)> yxzy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 3)> yxzz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 1)> yyxx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 2)> yyxy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 3)> yyxz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 1)> yyyx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 2)> yyyy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 3)> yyyz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 1)> yyzx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 2)> yyzy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 3)> yyzz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 1)> yzxx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 2)> yzxy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 3)> yzxz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 1)> yzyx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 2)> yzyy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 3)> yzyz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 1)> yzzx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 2)> yzzy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 3)> yzzz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 1)> zxxx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 2)> zxxy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 3)> zxxz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 1)> zxyx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 2)> zxyy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 3)> zxyz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 1)> zxzx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 2)> zxzy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 3)> zxzz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 1)> zyxx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 2)> zyxy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 3)> zyxz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 1)> zyyx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 2)> zyyy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 3)> zyyz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 1)> zyzx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 2)> zyzy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 3)> zyzz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 1)> zzxx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 2)> zzxy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 3)> zzxz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 1)> zzyx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 2)> zzyy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 3)> zzyz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 1)> zzzx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 2)> zzzy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 3)> zzzz;

vec<T, 2, math_internal::make_swizzle_options(O, 1, 1)> rr;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 2)> rg;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 3)> rb;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 1)> gr;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 2)> gg;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 3)> gb;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 1)> br;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 2)> bg;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 3)> bb;

vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 1)> rrr;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 2)> rrg;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 3)> rrb;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 1)> rgr;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 2)> rgg;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 3)> rgb;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 1)> rbr;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 2)> rbg;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 3)> rbb;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 1)> grr;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 2)> grg;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 3)> grb;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 1)> ggr;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 2)> ggg;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 3)> ggb;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 1)> gbr;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 2)> gbg;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 3)> gbb;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 1)> brr;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 2)> brg;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 3)> brb;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 1)> bgr;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 2)> bgg;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 3)> bgb;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 1)> bbr;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 2)> bbg;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 3)> bbb;

vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 1)> rrrr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 2)> rrrg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 3)> rrrb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 1)> rrgr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 2)> rrgg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 3)> rrgb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 1)> rrbr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 2)> rrbg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 3)> rrbb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 1)> rgrr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 2)> rgrg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 3)> rgrb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 1)> rggr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 2)> rggg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 3)> rggb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 1)> rgbr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 2)> rgbg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 3)> rgbb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 1)> rbrr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 2)> rbrg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 3)> rbrb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 1)> rbgr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 2)> rbgg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 3)> rbgb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 1)> rbbr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 2)> rbbg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 3)> rbbb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 1)> grrr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 2)> grrg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 3)> grrb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 1)> grgr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 2)> grgg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 3)> grgb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 1)> grbr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 2)> grbg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 3)> grbb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 1)> ggrr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 2)> ggrg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 3)> ggrb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 1)> gggr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 2)> gggg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 3)> gggb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 1)> ggbr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 2)> ggbg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 3)> ggbb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 1)> gbrr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 2)> gbrg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 3)> gbrb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 1)> gbgr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 2)> gbgg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 3)> gbgb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 1)> gbbr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 2)> gbbg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 3)> gbbb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 1)> brrr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 2)> brrg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 3)> brrb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 1)> brgr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 2)> brgg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 3)> brgb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 1)> brbr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 2)> brbg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 3)> brbb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 1)> bgrr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 2)> bgrg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 3)> bgrb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 1)> bggr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 2)> bggg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 3)> bggb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 1)> bgbr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 2)> bgbg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 3)> bgbb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 1)> bbrr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 2)> bbrg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 3)> bbrb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 1)> bbgr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 2)> bbgg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 3)> bbgb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 1)> bbbr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 2)> bbbg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 3)> bbbb;

