#pragma once


vec<T, 2, math_internal::make_swizzle_options(O, 1, 1)> xx;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 2)> xy;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 3)> xz;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 4)> xw;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 1)> yx;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 2)> yy;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 3)> yz;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 4)> yw;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 1)> zx;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 2)> zy;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 3)> zz;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 4)> zw;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 1)> wx;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 2)> wy;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 3)> wz;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 4)> ww;

vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 1)> xxx;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 2)> xxy;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 3)> xxz;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 4)> xxw;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 1)> xyx;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 2)> xyy;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 3)> xyz;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 4)> xyw;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 1)> xzx;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 2)> xzy;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 3)> xzz;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 4)> xzw;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 1)> xwx;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 2)> xwy;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 3)> xwz;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 4)> xww;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 1)> yxx;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 2)> yxy;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 3)> yxz;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 4)> yxw;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 1)> yyx;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 2)> yyy;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 3)> yyz;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 4)> yyw;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 1)> yzx;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 2)> yzy;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 3)> yzz;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 4)> yzw;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 1)> ywx;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 2)> ywy;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 3)> ywz;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 4)> yww;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 1)> zxx;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 2)> zxy;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 3)> zxz;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 4)> zxw;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 1)> zyx;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 2)> zyy;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 3)> zyz;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 4)> zyw;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 1)> zzx;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 2)> zzy;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 3)> zzz;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 4)> zzw;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 1)> zwx;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 2)> zwy;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 3)> zwz;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 4)> zww;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 1)> wxx;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 2)> wxy;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 3)> wxz;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 4)> wxw;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 1)> wyx;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 2)> wyy;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 3)> wyz;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 4)> wyw;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 1)> wzx;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 2)> wzy;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 3)> wzz;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 4)> wzw;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 1)> wwx;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 2)> wwy;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 3)> wwz;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 4)> www;

vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 1)> xxxx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 2)> xxxy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 3)> xxxz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 4)> xxxw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 1)> xxyx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 2)> xxyy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 3)> xxyz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 4)> xxyw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 1)> xxzx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 2)> xxzy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 3)> xxzz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 4)> xxzw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 1)> xxwx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 2)> xxwy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 3)> xxwz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 4)> xxww;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 1)> xyxx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 2)> xyxy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 3)> xyxz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 4)> xyxw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 1)> xyyx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 2)> xyyy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 3)> xyyz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 4)> xyyw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 1)> xyzx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 2)> xyzy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 3)> xyzz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 4)> xyzw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 1)> xywx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 2)> xywy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 3)> xywz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 4)> xyww;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 1)> xzxx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 2)> xzxy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 3)> xzxz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 4)> xzxw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 1)> xzyx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 2)> xzyy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 3)> xzyz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 4)> xzyw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 1)> xzzx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 2)> xzzy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 3)> xzzz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 4)> xzzw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 1)> xzwx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 2)> xzwy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 3)> xzwz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 4)> xzww;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 1)> xwxx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 2)> xwxy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 3)> xwxz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 4)> xwxw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 1)> xwyx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 2)> xwyy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 3)> xwyz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 4)> xwyw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 1)> xwzx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 2)> xwzy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 3)> xwzz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 4)> xwzw;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 1)> xwwx;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 2)> xwwy;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 3)> xwwz;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 4)> xwww;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 1)> yxxx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 2)> yxxy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 3)> yxxz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 4)> yxxw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 1)> yxyx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 2)> yxyy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 3)> yxyz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 4)> yxyw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 1)> yxzx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 2)> yxzy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 3)> yxzz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 4)> yxzw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 1)> yxwx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 2)> yxwy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 3)> yxwz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 4)> yxww;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 1)> yyxx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 2)> yyxy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 3)> yyxz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 4)> yyxw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 1)> yyyx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 2)> yyyy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 3)> yyyz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 4)> yyyw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 1)> yyzx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 2)> yyzy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 3)> yyzz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 4)> yyzw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 1)> yywx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 2)> yywy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 3)> yywz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 4)> yyww;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 1)> yzxx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 2)> yzxy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 3)> yzxz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 4)> yzxw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 1)> yzyx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 2)> yzyy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 3)> yzyz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 4)> yzyw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 1)> yzzx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 2)> yzzy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 3)> yzzz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 4)> yzzw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 1)> yzwx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 2)> yzwy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 3)> yzwz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 4)> yzww;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 1)> ywxx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 2)> ywxy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 3)> ywxz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 4)> ywxw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 1)> ywyx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 2)> ywyy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 3)> ywyz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 4)> ywyw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 1)> ywzx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 2)> ywzy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 3)> ywzz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 4)> ywzw;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 1)> ywwx;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 2)> ywwy;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 3)> ywwz;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 4)> ywww;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 1)> zxxx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 2)> zxxy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 3)> zxxz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 4)> zxxw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 1)> zxyx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 2)> zxyy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 3)> zxyz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 4)> zxyw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 1)> zxzx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 2)> zxzy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 3)> zxzz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 4)> zxzw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 1)> zxwx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 2)> zxwy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 3)> zxwz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 4)> zxww;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 1)> zyxx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 2)> zyxy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 3)> zyxz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 4)> zyxw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 1)> zyyx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 2)> zyyy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 3)> zyyz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 4)> zyyw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 1)> zyzx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 2)> zyzy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 3)> zyzz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 4)> zyzw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 1)> zywx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 2)> zywy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 3)> zywz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 4)> zyww;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 1)> zzxx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 2)> zzxy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 3)> zzxz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 4)> zzxw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 1)> zzyx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 2)> zzyy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 3)> zzyz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 4)> zzyw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 1)> zzzx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 2)> zzzy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 3)> zzzz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 4)> zzzw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 1)> zzwx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 2)> zzwy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 3)> zzwz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 4)> zzww;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 1)> zwxx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 2)> zwxy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 3)> zwxz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 4)> zwxw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 1)> zwyx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 2)> zwyy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 3)> zwyz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 4)> zwyw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 1)> zwzx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 2)> zwzy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 3)> zwzz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 4)> zwzw;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 1)> zwwx;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 2)> zwwy;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 3)> zwwz;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 4)> zwww;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 1)> wxxx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 2)> wxxy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 3)> wxxz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 4)> wxxw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 1)> wxyx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 2)> wxyy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 3)> wxyz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 4)> wxyw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 1)> wxzx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 2)> wxzy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 3)> wxzz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 4)> wxzw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 1)> wxwx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 2)> wxwy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 3)> wxwz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 4)> wxww;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 1)> wyxx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 2)> wyxy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 3)> wyxz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 4)> wyxw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 1)> wyyx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 2)> wyyy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 3)> wyyz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 4)> wyyw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 1)> wyzx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 2)> wyzy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 3)> wyzz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 4)> wyzw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 1)> wywx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 2)> wywy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 3)> wywz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 4)> wyww;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 1)> wzxx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 2)> wzxy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 3)> wzxz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 4)> wzxw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 1)> wzyx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 2)> wzyy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 3)> wzyz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 4)> wzyw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 1)> wzzx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 2)> wzzy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 3)> wzzz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 4)> wzzw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 1)> wzwx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 2)> wzwy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 3)> wzwz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 4)> wzww;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 1)> wwxx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 2)> wwxy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 3)> wwxz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 4)> wwxw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 1)> wwyx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 2)> wwyy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 3)> wwyz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 4)> wwyw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 1)> wwzx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 2)> wwzy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 3)> wwzz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 4)> wwzw;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 1)> wwwx;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 2)> wwwy;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 3)> wwwz;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 4)> wwww;

vec<T, 2, math_internal::make_swizzle_options(O, 1, 1)> rr;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 2)> rg;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 3)> rb;
vec<T, 2, math_internal::make_swizzle_options(O, 1, 4)> ra;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 1)> gr;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 2)> gg;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 3)> gb;
vec<T, 2, math_internal::make_swizzle_options(O, 2, 4)> ga;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 1)> br;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 2)> bg;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 3)> bb;
vec<T, 2, math_internal::make_swizzle_options(O, 3, 4)> ba;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 1)> ar;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 2)> ag;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 3)> ab;
vec<T, 2, math_internal::make_swizzle_options(O, 4, 4)> aa;

vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 1)> rrr;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 2)> rrg;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 3)> rrb;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 1, 4)> rra;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 1)> rgr;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 2)> rgg;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 3)> rgb;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 2, 4)> rga;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 1)> rbr;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 2)> rbg;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 3)> rbb;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 3, 4)> rba;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 1)> rar;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 2)> rag;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 3)> rab;
vec<T, 3, math_internal::make_swizzle_options(O, 1, 4, 4)> raa;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 1)> grr;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 2)> grg;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 3)> grb;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 1, 4)> gra;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 1)> ggr;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 2)> ggg;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 3)> ggb;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 2, 4)> gga;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 1)> gbr;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 2)> gbg;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 3)> gbb;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 3, 4)> gba;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 1)> gar;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 2)> gag;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 3)> gab;
vec<T, 3, math_internal::make_swizzle_options(O, 2, 4, 4)> gaa;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 1)> brr;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 2)> brg;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 3)> brb;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 1, 4)> bra;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 1)> bgr;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 2)> bgg;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 3)> bgb;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 2, 4)> bga;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 1)> bbr;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 2)> bbg;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 3)> bbb;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 3, 4)> bba;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 1)> bar;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 2)> bag;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 3)> bab;
vec<T, 3, math_internal::make_swizzle_options(O, 3, 4, 4)> baa;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 1)> arr;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 2)> arg;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 3)> arb;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 1, 4)> ara;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 1)> agr;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 2)> agg;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 3)> agb;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 2, 4)> aga;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 1)> abr;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 2)> abg;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 3)> abb;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 3, 4)> aba;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 1)> aar;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 2)> aag;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 3)> aab;
vec<T, 3, math_internal::make_swizzle_options(O, 4, 4, 4)> aaa;

vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 1)> rrrr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 2)> rrrg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 3)> rrrb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 1, 4)> rrra;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 1)> rrgr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 2)> rrgg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 3)> rrgb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 2, 4)> rrga;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 1)> rrbr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 2)> rrbg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 3)> rrbb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 3, 4)> rrba;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 1)> rrar;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 2)> rrag;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 3)> rrab;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 1, 4, 4)> rraa;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 1)> rgrr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 2)> rgrg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 3)> rgrb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 1, 4)> rgra;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 1)> rggr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 2)> rggg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 3)> rggb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 2, 4)> rgga;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 1)> rgbr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 2)> rgbg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 3)> rgbb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 3, 4)> rgba;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 1)> rgar;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 2)> rgag;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 3)> rgab;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 2, 4, 4)> rgaa;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 1)> rbrr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 2)> rbrg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 3)> rbrb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 1, 4)> rbra;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 1)> rbgr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 2)> rbgg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 3)> rbgb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 2, 4)> rbga;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 1)> rbbr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 2)> rbbg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 3)> rbbb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 3, 4)> rbba;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 1)> rbar;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 2)> rbag;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 3)> rbab;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 3, 4, 4)> rbaa;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 1)> rarr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 2)> rarg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 3)> rarb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 1, 4)> rara;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 1)> ragr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 2)> ragg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 3)> ragb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 2, 4)> raga;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 1)> rabr;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 2)> rabg;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 3)> rabb;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 3, 4)> raba;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 1)> raar;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 2)> raag;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 3)> raab;
vec<T, 4, math_internal::make_swizzle_options(O, 1, 4, 4, 4)> raaa;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 1)> grrr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 2)> grrg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 3)> grrb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 1, 4)> grra;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 1)> grgr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 2)> grgg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 3)> grgb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 2, 4)> grga;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 1)> grbr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 2)> grbg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 3)> grbb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 3, 4)> grba;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 1)> grar;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 2)> grag;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 3)> grab;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 1, 4, 4)> graa;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 1)> ggrr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 2)> ggrg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 3)> ggrb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 1, 4)> ggra;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 1)> gggr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 2)> gggg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 3)> gggb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 2, 4)> ggga;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 1)> ggbr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 2)> ggbg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 3)> ggbb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 3, 4)> ggba;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 1)> ggar;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 2)> ggag;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 3)> ggab;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 2, 4, 4)> ggaa;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 1)> gbrr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 2)> gbrg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 3)> gbrb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 1, 4)> gbra;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 1)> gbgr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 2)> gbgg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 3)> gbgb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 2, 4)> gbga;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 1)> gbbr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 2)> gbbg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 3)> gbbb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 3, 4)> gbba;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 1)> gbar;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 2)> gbag;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 3)> gbab;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 3, 4, 4)> gbaa;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 1)> garr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 2)> garg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 3)> garb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 1, 4)> gara;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 1)> gagr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 2)> gagg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 3)> gagb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 2, 4)> gaga;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 1)> gabr;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 2)> gabg;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 3)> gabb;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 3, 4)> gaba;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 1)> gaar;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 2)> gaag;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 3)> gaab;
vec<T, 4, math_internal::make_swizzle_options(O, 2, 4, 4, 4)> gaaa;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 1)> brrr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 2)> brrg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 3)> brrb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 1, 4)> brra;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 1)> brgr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 2)> brgg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 3)> brgb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 2, 4)> brga;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 1)> brbr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 2)> brbg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 3)> brbb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 3, 4)> brba;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 1)> brar;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 2)> brag;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 3)> brab;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 1, 4, 4)> braa;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 1)> bgrr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 2)> bgrg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 3)> bgrb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 1, 4)> bgra;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 1)> bggr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 2)> bggg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 3)> bggb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 2, 4)> bgga;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 1)> bgbr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 2)> bgbg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 3)> bgbb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 3, 4)> bgba;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 1)> bgar;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 2)> bgag;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 3)> bgab;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 2, 4, 4)> bgaa;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 1)> bbrr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 2)> bbrg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 3)> bbrb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 1, 4)> bbra;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 1)> bbgr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 2)> bbgg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 3)> bbgb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 2, 4)> bbga;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 1)> bbbr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 2)> bbbg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 3)> bbbb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 3, 4)> bbba;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 1)> bbar;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 2)> bbag;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 3)> bbab;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 3, 4, 4)> bbaa;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 1)> barr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 2)> barg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 3)> barb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 1, 4)> bara;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 1)> bagr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 2)> bagg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 3)> bagb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 2, 4)> baga;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 1)> babr;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 2)> babg;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 3)> babb;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 3, 4)> baba;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 1)> baar;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 2)> baag;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 3)> baab;
vec<T, 4, math_internal::make_swizzle_options(O, 3, 4, 4, 4)> baaa;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 1)> arrr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 2)> arrg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 3)> arrb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 1, 4)> arra;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 1)> argr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 2)> argg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 3)> argb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 2, 4)> arga;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 1)> arbr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 2)> arbg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 3)> arbb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 3, 4)> arba;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 1)> arar;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 2)> arag;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 3)> arab;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 1, 4, 4)> araa;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 1)> agrr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 2)> agrg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 3)> agrb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 1, 4)> agra;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 1)> aggr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 2)> aggg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 3)> aggb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 2, 4)> agga;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 1)> agbr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 2)> agbg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 3)> agbb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 3, 4)> agba;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 1)> agar;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 2)> agag;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 3)> agab;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 2, 4, 4)> agaa;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 1)> abrr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 2)> abrg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 3)> abrb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 1, 4)> abra;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 1)> abgr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 2)> abgg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 3)> abgb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 2, 4)> abga;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 1)> abbr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 2)> abbg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 3)> abbb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 3, 4)> abba;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 1)> abar;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 2)> abag;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 3)> abab;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 3, 4, 4)> abaa;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 1)> aarr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 2)> aarg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 3)> aarb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 1, 4)> aara;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 1)> aagr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 2)> aagg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 3)> aagb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 2, 4)> aaga;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 1)> aabr;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 2)> aabg;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 3)> aabb;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 3, 4)> aaba;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 1)> aaar;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 2)> aaag;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 3)> aaab;
vec<T, 4, math_internal::make_swizzle_options(O, 4, 4, 4, 4)> aaaa;

